region               = "us-east-2"
account              = "<userxx>"
vpc_name             = "vpc"
vpc_cidr             = "192.168.0.0/20"
public_subnet_a_name = "public-subnet-a"
public_subnet_a_cidr = "192.168.0.0/24"
route_table_name     = "public-route-table"